export * from "./IHtmlDocument";
export * from "./IReact";
export * from "./IUser";
export * from "./IEmpresa"
export * from "./ICiudad"
export * from "./IPrecio"
export * from "./ILlave"
export * from "./IHorario"
export * from "./IForms"
export * from "./IFormidable"
export * from "./IPublicacion"